/**
 * MOC Minute Sheet PDF — Mari Energies hierarchy approval record.
 * One row per approval level with name, position, action, timestamp, comments.
 */
const PDFDocument = require('pdfkit');
const { positionLabel } = require('./mocChains');

function fmt(d) {
  if (!d) return '—';
  const dt = new Date(d);
  return isNaN(dt) ? '—' : dt.toISOString().replace('T',' ').slice(0, 16) + ' UTC';
}
function fullName(u) {
  if (!u) return '—';
  return `${u.first_name || ''} ${u.last_name || ''}`.trim() || (u.email || '—');
}
function actionLabel(s) {
  if (s.status === 'approved')  return 'Approved';
  if (s.status === 'rejected')  return 'Rejected';
  if (s.status === 'cancelled') return 'Cancelled';
  if (s.status === 'pending')   return 'Pending';
  if (s.status === 'forwarded') return 'Forwarded';
  return s.status;
}
function actionColor(s) {
  return ({
    approved:  '#16a34a',
    rejected:  '#dc2626',
    cancelled: '#94a3b8',
    pending:   '#f59e0b',
    forwarded: '#7c3aed'
  })[s.status] || '#0f172a';
}

function streamMinuteSheet(moc, steps, res) {
  const doc = new PDFDocument({ margin: 36, size: 'A4', info: { Title: `${moc.moc_number} — Minute Sheet` } });
  doc.pipe(res);

  // Header
  doc.fontSize(16).fillColor('#0f172a').text('MARI ENERGIES — MOC MINUTE SHEET', { align: 'center' });
  doc.moveDown(0.2);
  doc.fontSize(9).fillColor('#475569').text(
    `MSP-HSE-08 Management of Change · ${moc.doc_kind === 'dispensation' ? 'Dispensation' : 'MOC'} Approval Record`,
    { align: 'center' }
  );
  doc.moveDown(0.6);

  // MOC summary box
  hr(doc);
  doc.fontSize(11).fillColor('#0f172a').text(moc.moc_number, { continued: true })
     .fillColor('#475569').fontSize(10).text(`   ·   ${moc.title}`);
  doc.moveDown(0.3);

  kvRow(doc, [
    ['Department / Field',  `${moc.department_code} / ${moc.field_name || '—'}`],
    ['Classification',      cap(moc.classification)],
    ['Risk Level',          cap(moc.risk_level)],
    ['Capital Project',     moc.is_capital_project ? 'Yes' : 'No']
  ]);
  kvRow(doc, [
    ['Duration',     cap(moc.duration)],
    ['Type',         (moc.type_subcategory || '—').replace(/_/g, ' ')],
    ['Category',     moc.category || '—'],
    ['Priority',     moc.priority || '—']
  ]);
  kvRow(doc, [
    ['Initiated',    fmt(moc.initiated_at)],
    ['Approved',     fmt(moc.approved_at)],
    ['Status',       cap(moc.status)],
    ['Stage',        String(moc.stage || 1)]
  ]);
  doc.moveDown(0.4);

  // Originator block
  hr(doc);
  doc.fontSize(11).fillColor('#0f172a').text('Originator (JRE)');
  doc.moveDown(0.2);
  doc.fontSize(10).fillColor('#475569').text(
    `${fullName(moc.originator)}   ·   ${moc.originator?.email || '—'}   ·   ${fmt(moc.initiated_at)}`
  );
  doc.moveDown(0.6);

  // Approval chain
  hr(doc);
  doc.fontSize(12).fillColor('#0f172a').text('Approval Chain');
  doc.moveDown(0.3);

  // Table header
  const widths = [22, 130, 110, 75, 100, 80];  // Lvl, Position, Name, Action, When, Comments
  const headers = ['#', 'Position', 'Reviewer', 'Action', 'Date / Time', 'Comments'];
  tableHeader(doc, headers, widths);

  steps.forEach((s, i) => {
    ensureSpace(doc, 24);
    const cells = [
      String(i + 1),
      positionLabel(s.position_code) || (s.step_type || '—'),
      fullName(s.assignee) +
        (s.original_assignee_user_id && s.original_assignee_user_id !== s.assignee_user_id
          ? ` (delegated)` : ''),
      actionLabel(s),
      s.decision_at ? fmt(s.decision_at) : '—',
      s.comments || ''
    ];
    tableRow(doc, cells, widths, i % 2 === 0, actionColor(s));
  });

  // Footer
  doc.moveDown(1);
  hr(doc);
  doc.fontSize(8).fillColor('#475569').text(
    'Generated by Mari Energies MOC system — MSP-HSE-08 Annexure-H Minute Sheet equivalent.',
    { align: 'center' }
  );
  doc.fontSize(8).fillColor('#94a3b8').text(`Generated: ${fmt(new Date())}`, { align: 'center' });

  doc.end();
}

// ── helpers ────────────────────────────────────
function hr(doc) {
  doc.strokeColor('#e2e8f0').lineWidth(0.5)
     .moveTo(doc.page.margins.left, doc.y)
     .lineTo(doc.page.width - doc.page.margins.right, doc.y).stroke();
  doc.moveDown(0.3);
}

function kvRow(doc, pairs) {
  const xStart = doc.page.margins.left;
  const widthEach = (doc.page.width - doc.page.margins.left - doc.page.margins.right) / pairs.length;
  const y = doc.y;
  pairs.forEach(([label, value], i) => {
    const x = xStart + i * widthEach;
    doc.fontSize(8).fillColor('#94a3b8').text(label, x, y, { width: widthEach - 4 });
    doc.fontSize(10).fillColor('#0f172a').text(String(value || '—'), x, y + 10, { width: widthEach - 4 });
  });
  doc.y = y + 26;
}

function tableHeader(doc, headers, widths) {
  const xStart = doc.page.margins.left;
  const totalW = widths.reduce((a, b) => a + b, 0);
  const y = doc.y;
  doc.rect(xStart, y - 2, totalW, 16).fill('#0f172a');
  let x = xStart + 5;
  headers.forEach((h, i) => {
    doc.fillColor('#fff').fontSize(8).text(h, x, y + 1, { width: widths[i] - 8, lineBreak: false });
    x += widths[i];
  });
  doc.y = y + 17;
}

function tableRow(doc, cells, widths, alt, actionFg) {
  const xStart = doc.page.margins.left;
  const totalW = widths.reduce((a, b) => a + b, 0);
  // Determine row height by tallest cell (comments may wrap).
  const heights = cells.map((c, i) => {
    return doc.fontSize(8).heightOfString(String(c ?? ''), { width: widths[i] - 8 });
  });
  const rowH = Math.max(16, Math.ceil(Math.max(...heights)) + 6);
  ensureSpace(doc, rowH);

  const y = doc.y;
  if (alt) doc.rect(xStart, y - 2, totalW, rowH).fill('#f8fafc');

  let x = xStart + 5;
  cells.forEach((c, i) => {
    const isAction = i === 3;
    doc.fillColor(isAction ? actionFg : '#0f172a').fontSize(8)
       .text(String(c ?? ''), x, y + 1, { width: widths[i] - 8 });
    x += widths[i];
  });
  doc.y = y + rowH;
}

function ensureSpace(doc, needed) {
  if (doc.y + needed > doc.page.height - doc.page.margins.bottom) {
    doc.addPage();
  }
}

function cap(s) {
  if (!s) return '—';
  return String(s).replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}

module.exports = { streamMinuteSheet };
